# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

include: ["_pages"]
github: [metadata]

title: Lazy Software Engineer
email: r07521529@g.ntu.edu.tw
description: >- # this means to ignore newlines until "baseurl:"
                覺得學過的東西忘掉很可惜，留點記錄在這
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imashelywu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

logo: "/assets/images/logo_test_rm.png"
masthead_title: "Still Constructing..."

author: Ashely Wu


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: "dirt" 

breadcrumbs: true 
breadcrumb_home_label : "Home"
breadcrumb_separator  : "/"

paginate: 2 # amount of posts to show
paginate_path: /page:num/

words_per_minute: 50

repository: "imashelywu/imashelywu.github.io"

header:
  image: /assets/images/wallpaper.jpg
  image_description: "A description of the image"

teaser: /assets/images/post_teaser.jpg

comments:
  provider: "utterances"
  utterances:
    #repo: "imashelywu/imashelywu.github.io.comments"
    repo: "imashelywu/testcomments"
    theme: "dark-blue" # "github-light"
    issue_term: "pathname"
    

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

 # _pages
  - scope:
      path: ""
      type: pages
    values:
      # layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
BASE_PATH : /assets/images